# Use the base image from the devcontainer definition
FROM mcr.microsoft.com/devcontainers/base:ubuntu

# Install the MySQL client
RUN apt update && apt install -y mysql-client

# Set working directory
WORKDIR /workspaces
